//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string CommentStatus_Approved {
            get {
                return ResourceManager.GetString("CommentStatus.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        internal static string CommentStatus_Spam {
            get {
                return ResourceManager.GetString("CommentStatus.Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        internal static string CommentStatus_Unapproved {
            get {
                return ResourceManager.GetString("CommentStatus.Unapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the Control Panel.
        /// </summary>
        internal static string Form_BackToControlPanel {
            get {
                return ResourceManager.GetString("Form_BackToControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my updates.
        /// </summary>
        internal static string Form_PostUpdate {
            get {
                return ResourceManager.GetString("Form_PostUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Form_Publish {
            get {
                return ResourceManager.GetString("Form_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Form_Save {
            get {
                return ResourceManager.GetString("Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as draft.
        /// </summary>
        internal static string Form_SaveAsDraft {
            get {
                return ResourceManager.GetString("Form_SaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Form_Update {
            get {
                return ResourceManager.GetString("Form_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existings sites.
        /// </summary>
        internal static string Home_Quickstart_ManageSites {
            get {
                return ResourceManager.GetString("Home_Quickstart_ManageSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new web site.
        /// </summary>
        internal static string Home_Quickstart_NewSite {
            get {
                return ResourceManager.GetString("Home_Quickstart_NewSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string Home_Quickstart_Title {
            get {
                return ResourceManager.GetString("Home_Quickstart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoggedUserLabel {
            get {
                return ResourceManager.GetString("LoggedUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me the new password.
        /// </summary>
        internal static string LoginResetPasswordButtonText {
            get {
                return ResourceManager.GetString("LoginResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been saved successfully!.
        /// </summary>
        internal static string Message_CategorySaved {
            get {
                return ResourceManager.GetString("Message_CategorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the message.
        /// </summary>
        internal static string Message_Close {
            get {
                return ResourceManager.GetString("Message_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new custom field has been saved successfully!.
        /// </summary>
        internal static string Message_CustomFieldSaved {
            get {
                return ResourceManager.GetString("Message_CustomFieldSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops, I&apos;m sorry but an error occured. Please retry or contact us to  notify what happened..
        /// </summary>
        internal static string Message_GenericError {
            get {
                return ResourceManager.GetString("Message_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories already defined.
        /// </summary>
        internal static string Message_NoCategories {
            get {
                return ResourceManager.GetString("Message_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no custom fields defined.
        /// </summary>
        internal static string Message_NoCustomField {
            get {
                return ResourceManager.GetString("Message_NoCustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tags already defined.
        /// </summary>
        internal static string Message_NoTags {
            get {
                return ResourceManager.GetString("Message_NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post has not yet tags associated.
        /// </summary>
        internal static string Message_NoTagsAssociated {
            get {
                return ResourceManager.GetString("Message_NoTagsAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no popular tags.
        /// </summary>
        internal static string Message_NoTagsPopular {
            get {
                return ResourceManager.GetString("Message_NoTagsPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page has been saved successfully!.
        /// </summary>
        internal static string Message_PageSaved {
            get {
                return ResourceManager.GetString("Message_PageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page has been updated!.
        /// </summary>
        internal static string Message_PageUpdated {
            get {
                return ResourceManager.GetString("Message_PageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been saved successfully!.
        /// </summary>
        internal static string Message_PostSaved {
            get {
                return ResourceManager.GetString("Message_PostSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been updated!.
        /// </summary>
        internal static string Message_PostUpdated {
            get {
                return ResourceManager.GetString("Message_PostUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that the domain {0} is already in use, please choose another one..
        /// </summary>
        internal static string Message_SiteHostNotUnique {
            get {
                return ResourceManager.GetString("Message_SiteHostNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new tag has been saved successfully!.
        /// </summary>
        internal static string Message_TagSaved {
            get {
                return ResourceManager.GetString("Message_TagSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been successfully created..
        /// </summary>
        internal static string Message_UserCreated {
            get {
                return ResourceManager.GetString("Message_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name isn&apos;t available because it is in use by an other user.
        /// </summary>
        internal static string Message_UserDisplayNameIsNotUnique {
            get {
                return ResourceManager.GetString("Message_UserDisplayNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email specified is in use by another user.
        /// </summary>
        internal static string Message_UserEmailIsNotUnique {
            get {
                return ResourceManager.GetString("Message_UserEmailIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed successfully..
        /// </summary>
        internal static string Message_UserPasswordChanged {
            get {
                return ResourceManager.GetString("Message_UserPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user data has been saved successfully!.
        /// </summary>
        internal static string Message_UserSaved {
            get {
                return ResourceManager.GetString("Message_UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Control Panel requires that JavaScript is enabled on this browser..
        /// </summary>
        internal static string NoScript_Description {
            get {
                return ResourceManager.GetString("NoScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the instructions at this link:.
        /// </summary>
        internal static string NoScript_Help {
            get {
                return ResourceManager.GetString("NoScript_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string NoScript_HelpLink {
            get {
                return ResourceManager.GetString("NoScript_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string NoScript_Title {
            get {
                return ResourceManager.GetString("NoScript_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a better experience using this site, please upgrade to a modern web browser..
        /// </summary>
        internal static string ObsoleteWarning_Body {
            get {
                return ResourceManager.GetString("ObsoleteWarning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using an outdated browser.
        /// </summary>
        internal static string ObsoleteWarning_Title {
            get {
                return ResourceManager.GetString("ObsoleteWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles_Label {
            get {
                return ResourceManager.GetString("Roles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string SiteStatus_Offline {
            get {
                return ResourceManager.GetString("SiteStatus.Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string SiteStatus_Online {
            get {
                return ResourceManager.GetString("SiteStatus.Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Down.
        /// </summary>
        internal static string SiteStatus_TemporaryDown {
            get {
                return ResourceManager.GetString("SiteStatus.TemporaryDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string WorkflowStatus_Draft {
            get {
                return ResourceManager.GetString("WorkflowStatus.Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string WorkflowStatus_Published {
            get {
                return ResourceManager.GetString("WorkflowStatus.Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string WorkflowStatus_Review {
            get {
                return ResourceManager.GetString("WorkflowStatus.Review", resourceCulture);
            }
        }
    }
}
