//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThemeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ThemeResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Archive.
        /// </summary>
        internal static string Archive_ForAuthor {
            get {
                return ResourceManager.GetString("Archive_ForAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive for the &amp;#8216;{0}&amp;#8217; Category.
        /// </summary>
        internal static string Archive_ForCategory {
            get {
                return ResourceManager.GetString("Archive_ForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive for {0}.
        /// </summary>
        internal static string Archive_ForDay {
            get {
                return ResourceManager.GetString("Archive_ForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive for {0}.
        /// </summary>
        internal static string Archive_ForMonth {
            get {
                return ResourceManager.GetString("Archive_ForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Tagged &amp;#8216;{0}&amp;#8217;.
        /// </summary>
        internal static string Archive_ForTag {
            get {
                return ResourceManager.GetString("Archive_ForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive for year {0}.
        /// </summary>
        internal static string Archive_ForYear {
            get {
                return ResourceManager.GetString("Archive_ForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user hasn&apos;t shared any biographical information.
        /// </summary>
        internal static string Author_NoBio {
            get {
                return ResourceManager.GetString("Author_NoBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all posts filed under.
        /// </summary>
        internal static string Category_LinkTitle {
            get {
                return ResourceManager.GetString("Category_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Comment_Author_Anonymous {
            get {
                return ResourceManager.GetString("Comment_Author_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string Comment_By {
            get {
                return ResourceManager.GetString("Comment_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the comment form is closed at this time..
        /// </summary>
        internal static string Comment_Closed {
            get {
                return ResourceManager.GetString("Comment_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Comments.
        /// </summary>
        internal static string Comment_CommentsNumber_More {
            get {
                return ResourceManager.GetString("Comment_CommentsNumber_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments off.
        /// </summary>
        internal static string Comment_CommentsNumber_Off {
            get {
                return ResourceManager.GetString("Comment_CommentsNumber_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Comment.
        /// </summary>
        internal static string Comment_CommentsNumber_One {
            get {
                return ResourceManager.GetString("Comment_CommentsNumber_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comments.
        /// </summary>
        internal static string Comment_CommentsNumber_Zero {
            get {
                return ResourceManager.GetString("Comment_CommentsNumber_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail (will not be published) (required).
        /// </summary>
        internal static string Comment_Email {
            get {
                return ResourceManager.GetString("Comment_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        internal static string Comment_LeaveAComment {
            get {
                return ResourceManager.GetString("Comment_LeaveAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment on.
        /// </summary>
        internal static string Comment_Link_CommentOn {
            get {
                return ResourceManager.GetString("Comment_Link_CommentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, comments are closed on this post!.
        /// </summary>
        internal static string Comment_Message_Closed {
            get {
                return ResourceManager.GetString("Comment_Message_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you already posted the same comment!.
        /// </summary>
        internal static string Comment_Message_DuplicateComment {
            get {
                return ResourceManager.GetString("Comment_Message_DuplicateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occured while saving your comment....
        /// </summary>
        internal static string Comment_Message_GenericError {
            get {
                return ResourceManager.GetString("Comment_Message_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill all the required field to comment..
        /// </summary>
        internal static string Comment_Message_ValidationErrors {
            get {
                return ResourceManager.GetString("Comment_Message_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (required).
        /// </summary>
        internal static string Comment_Name {
            get {
                return ResourceManager.GetString("Comment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments yet..
        /// </summary>
        internal static string Comment_NoComments {
            get {
                return ResourceManager.GetString("Comment_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Comment.
        /// </summary>
        internal static string Comment_Submit {
            get {
                return ResourceManager.GetString("Comment_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment_Type_Comment {
            get {
                return ResourceManager.GetString("Comment_Type_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pingback.
        /// </summary>
        internal static string Comment_Type_Pingback {
            get {
                return ResourceManager.GetString("Comment_Type_Pingback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackback.
        /// </summary>
        internal static string Comment_Type_Trackback {
            get {
                return ResourceManager.GetString("Comment_Type_Trackback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Comment_Website {
            get {
                return ResourceManager.GetString("Comment_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mail (required).
        /// </summary>
        internal static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        internal static string Contact_Message {
            get {
                return ResourceManager.GetString("Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent..
        /// </summary>
        internal static string Contact_Message_Sent {
            get {
                return ResourceManager.GetString("Contact_Message_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some validation errors occurred. Please confirm the fields and submit it again..
        /// </summary>
        internal static string Contact_Message_ValidationErrors {
            get {
                return ResourceManager.GetString("Contact_Message_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name (required).
        /// </summary>
        internal static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Contact_Subject {
            get {
                return ResourceManager.GetString("Contact_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Contact_Submit_Button {
            get {
                return ResourceManager.GetString("Contact_Submit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        internal static string Label_Archives {
            get {
                return ResourceManager.GetString("Label_Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        internal static string Label_Meta {
            get {
                return ResourceManager.GetString("Label_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular tags.
        /// </summary>
        internal static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the Homepage.
        /// </summary>
        internal static string Link_ReturnToTheHomePage {
            get {
                return ResourceManager.GetString("Link_ReturnToTheHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer Entries &amp;raquo;.
        /// </summary>
        internal static string Pager_Simple_NewerEntries {
            get {
                return ResourceManager.GetString("Pager_Simple_NewerEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;laquo; Older Entries.
        /// </summary>
        internal static string Pager_Simple_OlderEntries {
            get {
                return ResourceManager.GetString("Pager_Simple_OlderEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (more...).
        /// </summary>
        internal static string Post_MoreLinkText {
            get {
                return ResourceManager.GetString("Post_MoreLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        internal static string Post_PostedBy {
            get {
                return ResourceManager.GetString("Post_PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Post_PostedIn {
            get {
                return ResourceManager.GetString("Post_PostedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted in.
        /// </summary>
        internal static string Post_PostedIn2 {
            get {
                return ResourceManager.GetString("Post_PostedIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string Post_ReadMore {
            get {
                return ResourceManager.GetString("Post_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page &amp;raquo;.
        /// </summary>
        internal static string Search_NextPage {
            get {
                return ResourceManager.GetString("Search_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found. Try a different search..
        /// </summary>
        internal static string Search_NoItemsFound {
            get {
                return ResourceManager.GetString("Search_NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;laquo; Previous Page.
        /// </summary>
        internal static string Search_PreviousPage {
            get {
                return ResourceManager.GetString("Search_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topics.
        /// </summary>
        internal static string TagCloud_TitleTopics {
            get {
                return ResourceManager.GetString("TagCloud_TitleTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please come back later....
        /// </summary>
        internal static string _302_Message1 {
            get {
                return ResourceManager.GetString("_302_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is temporarily closed for maintenance. We&apos;ll reopen as soon as possible!.
        /// </summary>
        internal static string _302_Title {
            get {
                return ResourceManager.GetString("_302_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we were not able to find that page you were looking for....
        /// </summary>
        internal static string _404_Message1 {
            get {
                return ResourceManager.GetString("_404_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest that you try going back one page or visit our homepage instead..
        /// </summary>
        internal static string _404_Message2 {
            get {
                return ResourceManager.GetString("_404_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page that you&apos;re looking for either doesn&apos;t exist or has been moved..
        /// </summary>
        internal static string _404_Message3 {
            get {
                return ResourceManager.GetString("_404_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try browsing the navigation above, or try using the search bar at the top right..
        /// </summary>
        internal static string _404_Message4 {
            get {
                return ResourceManager.GetString("_404_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might wanna browse our site instead.
        /// </summary>
        internal static string _404_Message5 {
            get {
                return ResourceManager.GetString("_404_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404 - Not Found.
        /// </summary>
        internal static string _404_Title1 {
            get {
                return ResourceManager.GetString("_404_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Nothing here!.
        /// </summary>
        internal static string _404_Title2 {
            get {
                return ResourceManager.GetString("_404_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - PAGE NOT FOUND.
        /// </summary>
        internal static string _404_Title3 {
            get {
                return ResourceManager.GetString("_404_Title3", resourceCulture);
            }
        }
    }
}
